# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLoginfb():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_loginfb(self):
        self.driver.get("https://staging-partner-explore.misterb2b.com/login")
        self.driver.set_window_size(1319, 688)
        self.driver.find_element(By.ID, "ui-sign-in-email-input").click()
        self.driver.find_element(By.ID, "ui-sign-in-email-input").send_keys("misteraladinqa@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, ".firebaseui-id-submit").click()
        WebDriverWait(self.driver, 20).until(
            expected_conditions.visibility_of_element_located((By.ID, "ui-sign-in-password-input")))
        element = self.driver.find_element(By.ID, "ui-sign-in-password-input")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "ui-sign-in-password-input")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.ID, "ui-sign-in-password-input")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.ID, "ui-sign-in-password-input").click()
        self.driver.find_element(By.ID, "ui-sign-in-password-input").send_keys("@MisterA1")
        self.driver.find_element(By.CSS_SELECTOR, ".firebaseui-id-submit").click()
        WebDriverWait(self.driver, 30000).until(
            expected_conditions.presence_of_element_located((By.XPATH, "/html/body/div[3]/div[3]/div/div")))
        assert self.driver.find_element(By.XPATH, "/html/body/div[3]/div[3]/div/div/div[1]").text == "Logging in"
        self.driver.find_element(By.ID, "main__workboard").click()